# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Jobeet - Your best job board
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.css, bootstrap-theme.css, main.css]

  javascripts:    [jquery-2.1.3.min.js, bootstrap.js]

  has_layout:     true
  layout:         layout
